apiVersion: v1
kind: Service
metadata:
  name: htcondor-master-svallero
  namespace: svallero
spec:
  ports:
  - port: 9618
  selector:
    app: htcondor-master-svallero
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: htcondor-master-svallero
  namespace: svallero
spec:
  selector:
    matchLabels:
      app: htcondor-master-svallero
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: htcondor-master-svallero
    spec:
      containers:
      - image: svallero/htcondor:test
        imagePullPolicy: Always
        name: htc-master
        ports:
        - containerPort: 9618
          name: htc-master
        args:
        - "-m"
        - "-S"
        - "1234"
        - "-C"
        - "6"
        - "-D"
        - "htcondor-submitter-svallero"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 3
          periodSeconds: 3
